#Mulai
print("Apa keluaran dari operator bitwise berikut? ")
print("============================================")
print("x = 4")
print("y = 11")
x = 4
y = 11
print("============================================")
print("x =", x , "Mempunyai Binary :", format(x,"08b"))
print("")
print("No. 1")
print("Soal : x | y")
print("Hasil x | y adalah : ", x|y, "Dengan Binary :",format(x|y,"08b"))
print("")
print("No. 2")
print("Soal : x >> y")
print("Hasil x >> y adalah : ", x >> y, "Dengan Binary :",format(x >> y,"08b"))
print("")
print("No. 3")
print("Soal : x ^ y")
print("Hasil x ^ y adalah : ", x ^ y, "Dengan Binary :",format(x ^ y,"08b"))
print("")
print("No. 4")
print("Soal : ~ y")
print("Hasil ~ y adalah : ", ~ y, "Dengan Binary :",format(~ y,"08b"))
print("")
print("No. 5")
print("Soal : x & y")
print("Hasil x & y adalah : ", x & y, "Dengan Binary :",format(x & y,"08b"))
print("")
input("Klik enter untuk selesai :")

